execute sys.DBMS_REDEFINITION.CAN_REDEF_TABLE('HR', 'SEGMENTS', DBMS_REDEFINITION.CONS_USE_ROWID); 
execute sys.DBMS_REDEFINITION.CAN_REDEF_TABLE('HR', 'TABLES', DBMS_REDEFINITION.CONS_USE_ROWID); 
execute sys.DBMS_REDEFINITION.CAN_REDEF_TABLE('HR', 'OBJECTS', DBMS_REDEFINITION.CONS_USE_ROWID); 
