CREATE DATABASE orcl
   USER SYS IDENTIFIED BY oracle
   USER SYSTEM IDENTIFIED BY oracle
   LOGFILE GROUP 1 ('/oradata/orcl/redo01.log') SIZE 50M,
           GROUP 2 ('/oradata/orcl/redo02.log') SIZE 50M,
           GROUP 3 ('/oradata/orcl/redo03.log') SIZE 50M
   MAXLOGFILES 5
   MAXLOGMEMBERS 5
   MAXLOGHISTORY 1
   MAXDATAFILES 100
   CHARACTER SET US7ASCII
   NATIONAL CHARACTER SET AL16UTF16
   EXTENT MANAGEMENT LOCAL
   DATAFILE '/oradata/orcl/system01.dbf' SIZE 1024M 
   SYSAUX DATAFILE '/oradata/orcl/sysaux01.dbf' SIZE 1024M
   DEFAULT TABLESPACE users
      DATAFILE '/oradata/orcl/users01.dbf'
      SIZE 100M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED
   DEFAULT TEMPORARY TABLESPACE temp
      TEMPFILE '/oradata/orcl/temp01.dbf'
      SIZE 20M
   UNDO TABLESPACE UNDOTBS1
      DATAFILE '/oradata/orcl/undotbs01.dbf'
      SIZE 200M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED;
